spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            provider: kakao
            client-id: ${KAKAO_LOGIN_CLIENT_ID}
            client-secret: ${KAKAO_LOGIN_CLIENT_SECRET}
            client-name: 카카오 로그인
          naver:
            provider: naver
            client-id: ${NAVER_LOGIN_CLIENT_ID}
            client-secret: ${NAVER_LOGIN_CLIENT_SECRET}
            client-name: 네이버 로그인
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: id