spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            provider: kakao
            client-id: ${KAKAO_LOGIN_CLIENT_ID}
            client-secret: ${KAKAO_LOGIN_CLIENT_SECRET}
            client-name: 카카오 로그인
            scope:
              - profile_nickname
              - profile_image
              - friends
              - talk_message
              - talk_calendar
              - talk_calendar_task
          naver:
            provider: naver
            client-id: ${NAVER_LOGIN_CLIENT_ID}
            client-secret: ${NAVER_LOGIN_CLIENT_SECRET}
            client-name: 네이버 로그인
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          google:
            provider: google
            client-id: ${GOOGLE_LOGIN_CLIENT_ID}
            client-secret: ${GOOGLE_LOGIN_CLIENT_SECRET}
            client-name: 구글 로그인
            scope:
              - openid
              - profile
              - email
              - phone
              - address
          github:
            provider: github
            client-id: ${GITHUB_LOGIN_CLIENT_ID}
            client-secret: ${GITHUB_LOGIN_CLIENT_SECRET}
            client-name: 깃헙 로그인
            scope:
              - user
          okta:
            provider: okta
            client-id: ${OKTA_LOGIN_CLIENT_ID}
            client-secret: ${OKTA_LOGIN_CLIENT_SECRET}
            client_name: 옥타 로그인
            scope:
              - profile
              - email
              - openid
        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: id
          okta:
            issuer-uri: https://dev-6mq8u0r8y0tt1682.us.auth0.com/