logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      client:
        registration:
          oidc-client:
            provider: authorization-server
            client-id: oidc-client
            client-secret: secret
            scope:
              - openid
              - profile
        provider:
          authorization-server:
            issuer-uri: http://localhost:8080